version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: always
    env_file: .env
    environment:
      - POSTGRES_USER=$POSTGRESDB_USER
      - POSTGRES_PASSWORD=$POSTGRESDB_ROOT_PASSWORD
      - POSTGRES_DB=$POSTGRESDB_DATABASE
      - PGDATA=/var/lib/postgresql/data/postgres/
    ports:
      - "${POSTGRESDB_LOCAL_PORT}:${POSTGRESDB_DOCKER_PORT}"
    volumes:
      - db:/var/lib/postgresql/db
  app:
    depends_on:
      - postgresdb
    build:
      context: .
      dockerfile: docker/SocialMediaPlatform.Dockerfile
    restart: on-failure
    env_file: .env
    ports:
      - "${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.datasource.url"  : "jdbc:postgresql://postgresdb:${POSTGRESDB_DOCKER_PORT}/${POSTGRESDB_DATABASE}",
          "spring.datasource.username" : "$POSTGRESDB_USER",
          "spring.datasource.password" : "$POSTGRESDB_ROOT_PASSWORD",
          "spring.jpa.hibernate.ddl-auto" : "update",
          "jwt.secretKey" : "$JWT_SECRET_KEY",
          "jwt.expirationTime" : "$JWT_EXPIRATION_TIME",
          "spring.mail.host" : "$MAIL_HOST",
          "spring.mail.username" : "$MAIL_USERNAME",
          "spring.mail.password" : "$MAIL_PASSWORD",
          "spring.mail.port" : "$MAIL_PORT",
          "spring.mail.properties.mail.smtp.auth" : "$MAIL_SMTP_AUTH",
          "spring.mail.properties.mail.smtp.starttls.enable" : "$MAIL_SMTP_STARTTLS_ENABLE",
          "mail.tokenExpiration" : "${MAIL_TOKEN_EXPIRATION}"
        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
volumes:
  db: