
name: CI pipeline

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - main 

env:
  IMAGE: socialmediaplatform-image
  TAG: latest
  DOCKERFILE: ./docker/SocialMediaPlatform.Dockerfile
  CONTEXT: "."
  JDK_DISTRIBUTION: 'adopt'
  JDK_VERSION: '17'
  MAVEN_CACHE: maven

jobs:
  format:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: axel-op/googlejavaformat-action@v3.6.0
        with:
          args: "--skip-sorting-imports --replace"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JDK_VERSION }}
          cache: ${{ env.MAVEN_CACHE }}
          
      - name: Build with Maven
        run: mvn clean install -DskipTests=true

      - name: Build Docker Image
        run: docker build -t ${{ env.IMAGE }}:${{ env.TAG }} -f ${{ env.DOCKERFILE }} ${{ env.CONTEXT }}

  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      SPRING_DATASOURCE_URL: ${{ secrets.TEST_CONTAINER_URL}}
      SPRING_DATASOURCE_USERNAME: ${{ secrets.TEST_CONTAINER_USERNAME }}
      SPRING_DATASOURCE_PASSWORD: ${{ secrets.TEST_CONTAINER_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      EXPIRATION_TIME: ${{secrets.EXPIRATION_TIME }}
      MAIL_HOST: ${{ secrets.MAIL_HOST }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
      MAIL_PORT: ${{ secrets.MAIL_PORT }}
      MAIL_SMTP_AUTH: ${{ secrets.MAIL_SMTP_AUTH }}
      MAIL_SMTP_STARTTLS_ENABLE: ${{ secrets.MAIL_SMTP_STARTTLS_ENABLE }}
      MAIL_TOKEN_EXPIRATION: ${{ secrets.MAIL_TOKEN_EXPIRATION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: ${{ env.JDK_DISTRIBUTION }}
          java-version: ${{ env.JDK_VERSION }}
          cache: ${{ env.MAVEN_CACHE }}

      - name: Run tests
        run: mvn test -Dspring.profiles.active=remote-test-containers
